name: NatCat
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - requests
  - tqdm
  - jupyterlab
  - matplotlib
  - seaborn
  - cartopy
  - geopandas
  - shapely
  - climada
  - pillow
  - ipykernel
